version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pelaaja2
      - MONGO_PASSWORD=munpassu
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pelaaja2
      - MONGO_INITDB_ROOT_PASSWORD=munpassu
